### ISSUE TITLE
YAML format errors

### ISSUE THREAD

**Issue by dido18** [di-unipi-socc/TosKer#30]
The error returned by Tosker when  the `.yaml` file is not well formatted does not sat anything about where the error occurs.

This is the error returned by Tosker:
![tosca-parser](https://user-images.githubusercontent.com/9201530/31880612-5aba0680-b7e1-11e7-835f-35523c63e6cb.png)

At least the number of line where the error occur could be shown.

**Comment by lucarin91** [comment]
Can you upload the TOSCA file that gives this error?

**Comment by lucarin91** [comment]
This error was print when TosKer executes a get_input function, but the input was not defined. I will merge this whit another issue.
