### ISSUE TITLE
Files logs missing

### ISSUE THREAD

**Issue by dido18** [di-unipi-socc/TosKer#36]
Tosker does not put the `install.log` `stop.log` `uninstall.log` file in the `/tmp/tosker/{app}/{component}` directory.

These are the (usuall) files store in the directory.

`configure.log  configure.sh   create.log     install.sh     start.log      start.sh       state          stop.sh        uninstall.sh`

**Comment by lucarin91** [comment]
There is a log file for each one of the lifecycle operation of a software component. Thus they are:  `create.log`, `configure.log`, `start.log`, `stop.log`, `delete.log`.
